//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBR.OTPAuthenticator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HBR.OTPAuthenticator.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBR Authenticator.
        /// </summary>
        internal static string AboutAppName {
            get {
                return ResourceManager.GetString("AboutAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soporte tecnico y FAQ:.
        /// </summary>
        internal static string AboutSupportLabel {
            get {
                return ResourceManager.GetString("AboutSupportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://hbrgroup.com.do/soporte.html.
        /// </summary>
        internal static string AboutSupportURL {
            get {
                return ResourceManager.GetString("AboutSupportURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10/07/2020.
        /// </summary>
        internal static string AboutVersionDate {
            get {
                return ResourceManager.GetString("AboutVersionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión 1.1.0.
        /// </summary>
        internal static string AboutVersionInfo {
            get {
                return ResourceManager.GetString("AboutVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de eliminar esta clave?.
        /// </summary>
        internal static string AcceptDelete {
            get {
                return ResourceManager.GetString("AcceptDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave actual.
        /// </summary>
        internal static string ActualPassword {
            get {
                return ResourceManager.GetString("ActualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error agregando el autenticador, favor de validar la clave e intentarlo nuevamente..
        /// </summary>
        internal static string AddedFailed {
            get {
                return ResourceManager.GetString("AddedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticador agregado con exito.
        /// </summary>
        internal static string AddedSucccess {
            get {
                return ResourceManager.GetString("AddedSucccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nueva Clave.
        /// </summary>
        internal static string AddOTPTitle {
            get {
                return ResourceManager.GetString("AddOTPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El uso de login biométrico no está configurado en su dispositivo..
        /// </summary>
        internal static string BiometricUnavailable {
            get {
                return ResourceManager.GetString("BiometricUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar clave.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de deshabilitar el uso de login biométrico?.
        /// </summary>
        internal static string DisableBiometric {
            get {
                return ResourceManager.GetString("DisableBiometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de deshabilitar el uso de login para el acceso?.
        /// </summary>
        internal static string DisableLogin {
            get {
                return ResourceManager.GetString("DisableLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Nombre&quot; es obligatorio.
        /// </summary>
        internal static string EmptyLabel {
            get {
                return ResourceManager.GetString("EmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Clave&quot; es obligatorio.
        /// </summary>
        internal static string EmptySecret {
            get {
                return ResourceManager.GetString("EmptySecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código ingresado es incorrecto.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo QR leído no contiene un OTP válido..
        /// </summary>
        internal static string InvalidQR {
            get {
                return ResourceManager.GetString("InvalidQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        internal static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar uso de login.
        /// </summary>
        internal static string LoginEnabledText {
            get {
                return ResourceManager.GetString("LoginEnabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave manual.
        /// </summary>
        internal static string MenuManualCode {
            get {
                return ResourceManager.GetString("MenuManualCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código QR.
        /// </summary>
        internal static string MenuScanCode {
            get {
                return ResourceManager.GetString("MenuScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar acceso.
        /// </summary>
        internal static string MenuSetup {
            get {
                return ResourceManager.GetString("MenuSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva clave.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Claves.
        /// </summary>
        internal static string OTPListTitle {
            get {
                return ResourceManager.GetString("OTPListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave modificada con éxito.
        /// </summary>
        internal static string PasswordChangeSucces {
            get {
                return ResourceManager.GetString("PasswordChangeSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de ingresar la clave actual.
        /// </summary>
        internal static string PasswordEmptyActual {
            get {
                return ResourceManager.GetString("PasswordEmptyActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de ingresar la nueva clave.
        /// </summary>
        internal static string PasswordEmptyNew {
            get {
                return ResourceManager.GetString("PasswordEmptyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las claves  no coinciden, favor revisar la confirmación de la clave..
        /// </summary>
        internal static string PasswordErrorConfirm {
            get {
                return ResourceManager.GetString("PasswordErrorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave debe tener un mínimo de 4 caracteres..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave erronea, favor intentar nuevamente..
        /// </summary>
        internal static string PasswordNotActual {
            get {
                return ResourceManager.GetString("PasswordNotActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al leer el codigo QR..
        /// </summary>
        internal static string ScanQRError {
            get {
                return ResourceManager.GetString("ScanQRError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        internal static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave introducida es demasiado corta.
        /// </summary>
        internal static string ShortSecret {
            get {
                return ResourceManager.GetString("ShortSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basada en tiempo.
        /// </summary>
        internal static string TimeBased {
            get {
                return ResourceManager.GetString("TimeBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Clave.
        /// </summary>
        internal static string UpdateSecretCode {
            get {
                return ResourceManager.GetString("UpdateSecretCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizar Login Biométrico.
        /// </summary>
        internal static string UseBiometrics {
            get {
                return ResourceManager.GetString("UseBiometrics", resourceCulture);
            }
        }
    }
}
